### ISSUE TITLE
emailstop flag is ignored

### ISSUE THREAD

**Issue by hannaedelman** [CLAMP-IT/clampmail#10]
Hello,
The user field emailstop is ignored where checking whom to send emails.
We solved it by adding it here:
$everyone = get_enrolled_users($context, '', 0, user_picture::fields('u').' . ',u.emailstop');  // add emailstop

and check the field in the foreach loop:
if ($everyone[$userid]->emailstop == 0)

Hanna

**Comment by mackensen** [comment]
Thanks for the report. I guess I had assumed that `emailstop` was checked in email_to_user (I think I also expected that core would take that setting out in favor of messaging).

**Comment by nadavkav** [comment]
It is also ignored in the original quickmail project. weird.
