### ISSUE TITLE
Attachments with periods or ellipsis fail

### ISSUE THREAD

**Issue by mackensen** [CLAMP-IT/clampmail#13]
If an attachment includes one or more periods Moodle will fail to send it (something like `foo..docx`):

```
Error in attachment.  User attempted to attach a filename with a unsafe name.
```

There's two ways to solve this:

1. Prevent the upload in the first place
1. Modify the filename on send

Additional periods in the filename are bad practice, period, so I'm inclined toward the first solution.

**Comment by kwiliarty** [comment]
Can we provide a useful message if we follow option 1?

**Comment by mackensen** [comment]
I'm working from the assumption that we can add custom validation to the upload form element.

**Comment by kwiliarty** [comment]
That would be address my only concern.

**Comment by mackensen** [comment]
Pinging @kwiliarty. The filemanager element doesn't support the kind of validation I hoped for. I went the alternative solution of stripping excess periods when sending the email.

**Comment by kwiliarty** [comment]
That works. Thanks for following up.
