### ISSUE TITLE
Is it possible to interpret Markdown emails as HTML?

### ISSUE THREAD

**Issue by kwiliarty** [CLAMP-IT/clampmail#14]
If a user has chosen 'Plain text area' as their favored text editor in their profile preferences they will be able to choose Markdown as one of the formats in which to compose an email in clampmail, but the email will not be sent as interpreted Markdown. Instead the markup and line breaks will all be run into one line like so:
```
# This should be a heading one ## And this a heading 2 Some text, a list: - Thing one - Thing two
```
Is it possible to compose in Markdown to be delivered as HTML, or at least to honor the line breaks?

**Comment by mackensen** [comment]
Confirmed regression from #8
