### ISSUE TITLE
Alt text for Quickmail menu icons is the same as the menu text

### ISSUE THREAD

**Issue by NukeHavoc** [CLAMP-IT/clampmail#18]
The alternative text for the Quickmail icons are the same as the adjacment menu text. Alternative text that is the same as nearby or adjacent text will be presented multiple times to screen readers or when images are unavailable.

Proposed fix: Change the alt text for the images to empty/null (e.g. alt="") because the content of the image is already provided in context through text. 

Alternatively, linked images may often be combined with the adjacent text into one link, in which case the image may be given null/empty alternative text (alt="").

See the WebAIM standards page for more information: http://webaim.org/standards/wcag/checklist#sc1.1.1

Example (includes highlighted notice info from WAVE):

<img width="266" alt="quickmail-block-alt-text-equals-menu-text" src="https://cloud.githubusercontent.com/assets/808825/16241718/fe31e126-37bc-11e6-9aad-c190b336a073.png">

**Comment by mackensen** [comment]
See also https://tracker.moodle.org/browse/MDL-46226.
