### ISSUE TITLE
Role filter with one teacher

### ISSUE THREAD

**Issue by willylee** [CLAMP-IT/clampmail#4]
If you are the only teacher in a course and try to use the role filter to choose all teachers for a course, the filter will not change state until the browser window loses focus.

1. Compose new message
1. Choose a section or "Not in a section" 
1. Select the "Teacher" role in the role filter drop down

At this point, the students are not deselected unless you click outside your browser window.

Weird.

**Comment by mackensen** [comment]
I didn't do anything specific to address this, but the issue no longer occurs in 3.1.
