### ISSUE TITLE
Enable/Disable Groups

### ISSUE THREAD

**Issue by jasonalley** [CLAMP-IT/clampmail#7]
Currently clampmail–at Lafayette at least–behaves as follows:

* When there are no groups in a class, the student roll has the ability to message the entire class using Quickmail
* When students are placed in groups, they are able to message only students in their group.
* When groups are used in a Moodle course, but a student is not a member of any group, this student is able to message only other students also not belonging to a group.

So, here's my feature request:

* When there are no groups in a class, the student roll has the ability to message the entire class using Quickmail (the same as it is now)
* When students are placed in groups, the teacher can select whether or not to enable Group mode similar to a discussion forum:
 * With Group mode enabled, students are able to message only students in their group.
 * With Group mode disabled, students are able to message the entire class.

Please let me know if this requires more of a conversation. Thanks!

**Comment by mackensen** [comment]
@jasonalley #17 captures this request, yes?

**Comment by jasonalley** [comment]
Yes, #17 captures it well. Thanks.
